import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // General / Tabs
      'app_title': 'ملتقى التجار',
      'home': 'الرئيسية',
      'cart': 'السلة',
      'wishlist': 'المفضلة',
      'profile': 'حسابي',
      'settings': 'الإعدادات',
      'currency': 'ريال يمني',
      'back': 'رجوع',
      'search_hint': 'البحث عن منتجات أو محلات...',
      'all_categories': 'جميع الأقسام',
      'view_all': 'عرض الكل',

      // Splash / Auth
      'welcome_title': 'ابدأ الآن',
      'welcome_subtitle': 'مرحباً بك في عالم التسوق... كل ما تبحث عنه أقرب مما تتخيل',
      'login_title': 'تسجيل الدخول',
      'login_subtitle': 'مرحباً بك مجدداً في ملتقى التجار',
      'email': 'البريد الإلكتروني',
      'email_hint': 'أدخل البريد الإلكتروني',
      'username_hint': 'أدخل اسم المستخدم',
      'password': 'كلمة المرور',
      'password_hint': 'أدخل كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login_btn': 'تسجيل الدخول',
      'no_account': 'ليس لديك حساب؟',
      'create_account': 'إنشاء حساب جديد',
      'account_type': 'نوع الحساب',
      'buyer': 'مشتري',
      'merchant': 'تاجر',
      'full_name': 'الاسم الكامل',
      'full_name_hint': 'أدخل الاسم الكامل',
      'phone_number': 'رقم الهاتف',
      'phone_number_hint': 'أدخل رقم الهاتف',
      'address': 'العنوان',
      'address_hint': 'أدخل العنوان بالتفصيل',
      'confirm_password': 'تأكيد كلمة المرور',
      'confirm_password_hint': 'أعد كتابة كلمة المرور',
      'register_btn': 'إنشاء الحساب',
      'already_have_account': 'هل لديك حساب بالفعل؟',
      'validation_email': 'الرجاء إدخال البريد الإلكتروني',
      'validation_password': 'الرجاء إدخال كلمة المرور',
      'validation_name': 'الرجاء إدخال الاسم الكامل',
      'validation_phone': 'الرجاء إدخال رقم الهاتف',
      'validation_address': 'الرجاء إدخال العنوان',
      'validation_confirm_password': 'الرجاء تأكيد كلمة المرور',
      'validation_password_mismatch': 'كلمة المرور غير متطابقة',
      'field_required': '* الحقل مطلوب',
      'or_via': 'أو عبر',
      'complete_fields_msg': 'الرجاء إكمال جميع الحقول',

      // Dashboard
      'best_sellers': 'المنتجات الأكثر مبيعاً',
      'trusted_shops': 'المحلات الموثوقة',
      'add_to_cart': 'أضف للسلة',
      'fashion': 'أزياء وملابس',
      'electronics': 'أجهزة إلكترونية',
      'cosmetics': 'عطور ومستحضرات تجميل',
      'shoes': 'أحذية وحقائب',
      'supermarket': 'سوبرماركت وغذاء',

      // Cart
      'shopping_cart': 'سلة التسوق',
      'empty_cart': 'السلة فارغة',
      'empty_cart_msg': 'تصفح المنتجات وأضفها إلى السلة',
      'go_shopping': 'الذهاب للتسوق',
      'order_summary': 'ملخص الطلب',
      'subtotal': 'المجموع الفرعي',
      'delivery_fee': 'رسوم التوصيل',
      'total': 'الإجمالي',
      'checkout_btn': 'متابعة عملية الشراء',
      'delete_confirm_title': 'تأكيد حذف المنتج؟',
      'delete_confirm_msg': 'هل أنت متأكد من حذف هذا المنتج من السلة؟',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'edit': 'تعديل',
      'hide': 'إخفاء',
      'save': 'حفظ',
      'add_products': 'إضافة منتجات',

      // Checkout
      'checkout': 'إتمام الشراء',
      'delivery_info': 'معلومات التوصيل',
      'contact_number': 'رقم التواصل',
      'payment_method': 'طريقة الدفع',
      'cod': 'الدفع عند الاستلام',
      'mobile_wallet': 'محفظة جوال (كريمي، فلوسك...)',
      'confirm_order': 'تأكيد الطلب',
      'success_order_title': 'تم إرسال طلبك بنجاح!',
      'success_order_msg': 'شكراً لك على التسوق معنا. يمكنك متابعة حالة طلبك من صفحة الطلبات.',
      'back_home': 'العودة للرئيسية',

      // Profile
      'username': 'اسم المستخدم',
      'user_phone': 'رقم الهاتف',
      'user_address': 'العنوان',
      'light_theme': 'المظهر الفاتح',
      'app_lock': 'قفل التطبيق',
      'enter_pin': 'الرجاء إدخال رمز الأمان',
      'confirm_pin': 'تأكيد رمز الأمان',
      'set_pin': 'تعيين رمز الأمان',
      'pin_mismatch': 'رمز الأمان غير متطابق',
      'auth_reason': 'الرجاء تأكيد هويتك لفتح التطبيق',
      'incorrect_pin': 'رمز الأمان غير صحيح',
      'enable_app_lock_first': 'يجب تفعيل قفل التطبيق أولاً',
      'biometrics_not_supported': 'البصمة غير مدعومة على هذا الجهاز',
      'fingerprint': 'تفعيل بصمة الإصبع',
      'language': 'اللغة',
      'privacy_policy': 'سياسة الخصوصية',
      'switch_to_merchant': 'تبديل لـ واجهة التاجر (تجريبي)',
      'logout': 'تسجيل الخروج',
      'logout_confirm_title': 'تسجيل الخروج',
      'logout_confirm_msg': 'هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',
      'confirm': 'تأكيد',

      // Merchant Dashboard
      'merchant_dashboard': 'لوحة تحكم التاجر',
      'welcome_merchant': 'مرحباً،',
      'total_sales': 'إجمالي المبيعات',
      'orders_count': 'عدد الطلبات',
      'active_products': 'المنتجات النشطة',
      'new_orders': 'الطلبات الجديدة',
      'latest_orders': 'أحدث الطلبات',
      'top_selling': 'المنتجات الأكثر مبيعاً',
      'add_product_nav': 'إضافة منتج',
      'manage_products_nav': 'إدارة المنتجات',
      'manage_orders_nav': 'إدارة الطلبات',
      'store_settings_nav': 'إعدادات المتجر',
      'dashboard_nav': 'لوحة التحكم',
      'products_nav': 'منتجاتي',
      'orders_nav': 'الطلبات',

      // Merchant Features
      'add_new_product': 'إضافة منتج جديد',
      'product_name': 'اسم المنتج',
      'product_name_hint': 'أدخل اسم المنتج',
      'product_price': 'سعر المنتج',
      'product_price_hint': 'أدخل سعر المنتج بالريال اليمني',
      'product_category': 'قسم المنتج',
      'select_category': 'اختر القسم',
      'product_desc': 'وصف المنتج',
      'product_desc_hint': 'أدخل تفاصيل ووصف المنتج بشكل مفصل...',
      'product_image': 'صورة المنتج',
      'upload_image': 'ارفع صورة المنتج',
      'save_product': 'حفظ ونشر المنتج',
      'edit_product': 'تعديل المنتج',
      'delete_product': 'حذف المنتج',
      'merchant_products': 'إدارة منتجاتي',
      'merchant_orders': 'إدارة الطلبات المستلمة',
      'store_setup': 'إعداد متجري',
      'store_name': 'اسم المتجر',
      'store_name_hint': 'أدخل اسم متجرك التجاري',
      'store_desc': 'وصف المتجر والنشاط',
      'store_desc_hint': 'اكتب نبذة عن متجرك والمنتجات التي تبيعها...',
      'store_phone': 'رقم هاتف المتجر للتواصل',
      'store_address': 'عنوان المتجر الرئيسي',
      'save_store_settings': 'حفظ إعدادات المتجر',
      'order_id': 'رقم الطلب',
      'customer': 'العميل',
      'status': 'الحالة',
      'order_details': 'تفاصيل الطلب',
      'order_status_pending': 'قيد الانتظار',
      'order_status_accepted': 'مقبول',
      'order_status_shipped': 'جاري التوصيل',
      'order_status_completed': 'مكتمل',
      'order_status_cancelled': 'ملغي',
      'change_status': 'تغيير الحالة',

      // Product Details
      'product_details': 'تفاصيل المنتج',
      'quantity': 'الكمية',
      'description': 'الوصف',
      'buy_now': 'شراء الآن',
      'added_to_cart_msg': 'تم إضافة المنتج إلى السلة بنجاح!',

      // Notifications / Wishlist / Orders (User)
      'notifications': 'الإشعارات',
      'no_notifications': 'لا توجد إشعارات جديدة',
      'my_wishlist': 'قائمتي المفضلة',
      'empty_wishlist': 'المفضلة فارغة',
      'empty_wishlist_msg': 'اضغط على أيقونة القلب في المنتجات لإضافتها هنا',
      'my_orders': 'طلباتي',
      'no_orders': 'لا توجد طلبات سابقة',

      // Checkout Extra
      'payment': 'الدفع',
      'requested_products': 'المنتجات المطلوبة',
      'address_label': 'العنوان',
      'delivery_label': 'التوصيل',
      'subtotal_products': 'المجموع الفرعي للمنتجات',
      'select_delivery_address': 'اختر عنوان التوصيل',
      'add_new_address': 'إضافة عنوان جديد',
      'select_delivery_method': 'اختر طريقة التوصيل',
      'enter_full_address': 'أدخل العنوان بالكامل',
      'add': 'إضافة',
      'select_address_msg': 'الرجاء اختيار عنوان التوصيل',
      'order_confirmed_title': 'تم تأكيد الطلب بنجاح!',
      'order_confirmed_msg': 'سيصلك إشعار عند تجهيز الطلب',
      'back_to_cart': 'العودة إلى السلة',
      'fast_delivery': 'توصيل سريع',
      'normal_delivery': 'توصيل عادي',
      'store_pickup': 'استلام من المتجر',
      'al_kuraimi': 'الكريمي',
      'yemen_kuwait': 'اليمن والكويت',
      'my_wallet_pay': 'الدفع عبر\nمحفظتي',

      // Cart Extra
      'delete_all': 'حذف الكل',
      'products_count': 'منتجات',
      'free': 'مجاني',
      'continue_shopping': 'متابعة التسوق',
      'clear_cart_title': 'تفريغ السلة',
      'clear_cart_msg': 'هل أنت متأكد من رغبتك في إفراغ سلة التسوق؟',
      'cart_deleted_msg': 'تم حذف المنتج من السلة',
      'cart_cleared_msg': 'تم تفريغ السلة',
      'cart_empty_error': 'سلة التسوق فارغة، أضف بعض المنتجات أولاً',

      // Dashboard Extra
      'search_here': 'بحث هنا...',
      'select_your_location': 'تحديد موقعك',
      'confirm_location': 'تأكيد الموقع',
      'detecting_location': 'جاري تحديد الموقع...',
      'location_from_map': 'موقع مخصص المختار من الخريطة',
      'welcome_default': 'أهلاً وسهلاً أمة الله محمد',
      'welcome_user': 'أهلاً وسهلاً',
      'discount_promo': 'خصم من 40 إلى 50%',
      'promo_available': 'متوفر الآن في المنتج',
      'all_colors': 'جميع الألوان',
      'shop_now_btn': 'تسوق الان',
      'added_to_favorites': 'تمت الإضافة إلى المفضلة',
      'removed_from_favorites': 'تمت الإزالة من المفضلة',
      'search_by_category': 'ابحث حسب القسم',
      'most_popular_brands': 'أشهر العلامات التجارية',
      'shop_by_brand': 'تسوق حسب الماركة',
      'featured_for_you': 'مختارات مميزة لك 🔥',
      'special_choices': 'مختارات خاصة',

      // Merchant Dashboard Extra
      'statistics': 'الاحصائيات',
      'earnings': 'الأرباح',
      'daily': 'يومياً',

      // Merchant Orders Extra
      'view_details': 'عرض التفاصيل',
      'order_number': 'رقم الطلب #',
      'suspend': 'تعليق',

      // Store Setup Extra
      'store_info': 'معلومات المتجر',
      'setup_store_intro': 'ابدأ إعداد متجرك بخطوة معنا',
      'complete_later': 'التكملة لاحقاً',
      'next': 'التالي',
      'finish': 'انهاء',
      'select_activity_type': 'اختر نوع النشاط',
      'add_logo_here': 'أضف شعارك هنا',
      'update_location': 'تحديث الموقع',
      'select_address': 'اختر العنوان',
      'primary': 'الأساسي',
      'add_branch': 'اضافة فرع',

      // Notifications Extra
      'today': 'اليوم',
      'yesterday': 'أمس',
      'mark_as_read': 'تحديد كمقروء',
      'notification_type_promo': 'تنبيه العروض',
      'notification_type_order': 'تحديث الطلب',
      'notification_type_admin': 'رسالة إدارية',
      'notification_type_remind': 'تذكير',
      'notification_type_welcome': 'ترحيب',
      'notification_title_1': 'عروض حصرية لك!',
      'notification_title_2': 'تم شحن طلبك',
      'notification_title_3': 'تحديث سياسة الخصوصية',
      'notification_title_4': 'تخفيضات نهاية الأسبوع',
      'notification_title_5': 'منتجات في سلتك',
      'notification_title_6': 'أهلاً بك في ملتقى التجار',
      'notification_desc_1': 'تصفح أحدث المنتجات والعروض المميزة بأسعار لا تفوت.',
      'notification_desc_2': 'طلبك رقم #1024 في الطريق إليك، تتبع الشحنة الآن.',
      'notification_desc_3': 'يرجى مراجعة التحديثات الجديدة في سياسة الخصوصية.',
      'notification_desc_4': 'استمتع بتخفيضات تصل إلى 50% على جميع الأقسام.',
      'notification_desc_5': 'لا تنسَ إتمام عملية الشراء للمنتجات في سلتك.',
      'notification_desc_6': 'يسعدنا انضمامك إلينا، ابدأ رحلة التسوق الآن!',
      'time_2h_ago': 'قبل ساعتين',
      'time_4h_ago': 'قبل 4 ساعات',
      'time_8h_ago': 'قبل 8 ساعات',
      'time_10h_ago': 'قبل 10 ساعات',
      'time_yesterday_morning': 'أمس 09:30 AM',
      'time_yesterday_early': 'أمس 08:00 AM',

      // Products Extra
      'completed': 'مكتملة',
      'colors': 'الألوان',
      'sizes': 'الأحجام',
      'buy_product': 'شراء المنتج',
      'ratings': 'تقييم',
      'wishlist_limit_msg': 'لا يمكن تثبيت أكثر من 10 منتجات',

      // Mock Data
      'mock_order_date': 'الخميس 7 أبريل 2026 • الساعة 10:25 AM',
      'mock_address_1': 'شارع الرياض، جوار مكتبة القلم الذهبي',
      'mock_address_2': 'شارع الرباط، جوار مكتبة القلم الذهبي',
      'mock_address_3': 'شارع الستين، مقابل مجمع الأبراج',
      'mock_address_4': 'حي السعادة، شارع النخيل، مبنى 5',
      'mock_address_5': 'شارع الرباط، جامعة الرازي',
      'mock_product_name': 'اسم المنتج المكون من خمس كلمات أو أكثر',
      'mock_product_short': 'اسم المنتج المكون من خمس كلمات',
      'mock_product_modern': 'منتج عصري',
      'mock_product_modern_style': 'تيشيرت ستايل عصري',
      'mock_product_modern_tshirt': 'تيشيرت عصري',
      'mock_product_test': 'اسم المنتج التجريبي',
      'mock_product_desc': 'فانيلة قطنية بتصميم بسيط وأنيق، مريحة للارتداء اليومي وتناسب جميع الإطلالات.',

      // Category Names
      'men_clothing': 'ملابس رجالية',
      'women_clothing': 'ملابس نسائية',
      'handbags': 'حقائب يد',
      'shoes_cat': 'أحذية',
      'children_clothing': 'ملابس أطفال',
      'accessories': 'اكسسوارات',
    },
    'en': {
      // General / Tabs
      'app_title': 'Tujjar Forum',
      'home': 'Home',
      'cart': 'Cart',
      'wishlist': 'Wishlist',
      'profile': 'Profile',
      'settings': 'Settings',
      'currency': 'YER',
      'back': 'Back',
      'search_hint': 'Search for products or shops...',
      'all_categories': 'All Categories',
      'view_all': 'View All',

      // Splash / Auth
      'welcome_title': 'Start Now',
      'welcome_subtitle': 'Welcome to the world of shopping... everything you look for is closer than you think',
      'login_title': 'Login',
      'login_subtitle': 'Welcome back to Tujjar Forum',
      'email': 'Email Address',
      'email_hint': 'Enter email address',
      'username_hint': 'Enter username',
      'password': 'Password',
      'password_hint': 'Enter password',
      'forgot_password': 'Forgot password?',
      'login_btn': 'Login',
      'no_account': 'Don\'t have an account?',
      'create_account': 'Create New Account',
      'account_type': 'Account Type',
      'buyer': 'Buyer',
      'merchant': 'Merchant',
      'full_name': 'Full Name',
      'full_name_hint': 'Enter full name',
      'phone_number': 'Phone Number',
      'phone_number_hint': 'Enter phone number',
      'address': 'Address',
      'address_hint': 'Enter detailed address',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Retype password',
      'register_btn': 'Create Account',
      'already_have_account': 'Already have an account?',
      'validation_email': 'Please enter email address',
      'validation_password': 'Please enter password',
      'validation_name': 'Please enter full name',
      'validation_phone': 'Please enter phone number',
      'validation_address': 'Please enter address',
      'validation_confirm_password': 'Please confirm password',
      'validation_password_mismatch': 'Passwords do not match',
      'field_required': '* Field required',
      'or_via': 'Or via',
      'complete_fields_msg': 'Please complete all fields',

      // Dashboard
      'best_sellers': 'Best Selling Products',
      'trusted_shops': 'Trusted Shops',
      'add_to_cart': 'Add to Cart',
      'fashion': 'Fashion & Clothes',
      'electronics': 'Electronics',
      'cosmetics': 'Perfumes & Cosmetics',
      'shoes': 'Shoes & Bags',
      'supermarket': 'Supermarket & Food',

      // Cart
      'shopping_cart': 'Shopping Cart',
      'empty_cart': 'Your cart is empty',
      'empty_cart_msg': 'Browse products and add them to cart',
      'go_shopping': 'Go Shopping',
      'order_summary': 'Order Summary',
      'subtotal': 'Subtotal',
      'delivery_fee': 'Delivery Fee',
      'total': 'Total',
      'checkout_btn': 'Proceed to Checkout',
      'delete_confirm_title': 'Confirm delete item?',
      'delete_confirm_msg': 'Are you sure you want to delete this item from cart?',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'hide': 'Hide',
      'save': 'Save',
      'add_products': 'Add Products',

      // Checkout
      'checkout': 'Checkout',
      'delivery_info': 'Delivery Information',
      'contact_number': 'Contact Number',
      'payment_method': 'Payment Method',
      'cod': 'Cash on Delivery',
      'mobile_wallet': 'Mobile Wallet (Kuraimi, Floosak...)',
      'confirm_order': 'Confirm Order',
      'success_order_title': 'Your order has been sent successfully!',
      'success_order_msg': 'Thank you for shopping with us. You can track your order status in the orders page.',
      'back_home': 'Back to Home',

      // Profile
      'username': 'Username',
      'user_phone': 'Phone Number',
      'user_address': 'Address',
      'light_theme': 'Light Theme',
      'app_lock': 'App Lock',
      'enter_pin': 'Please enter security PIN',
      'confirm_pin': 'Confirm security PIN',
      'set_pin': 'Set security PIN',
      'pin_mismatch': 'PIN code mismatch',
      'auth_reason': 'Please authenticate to unlock the app',
      'incorrect_pin': 'Incorrect PIN code',
      'enable_app_lock_first': 'App Lock must be enabled first',
      'biometrics_not_supported': 'Biometrics not supported on this device',
      'fingerprint': 'Enable Fingerprint',
      'language': 'Language',
      'privacy_policy': 'Privacy Policy',
      'switch_to_merchant': 'Switch to Merchant Interface (Beta)',
      'logout': 'Logout',
      'logout_confirm_title': 'Logout',
      'logout_confirm_msg': 'Are you sure you want to logout of your account?',
      'confirm': 'Confirm',

      // Merchant Dashboard
      'merchant_dashboard': 'Merchant Dashboard',
      'welcome_merchant': 'Welcome,',
      'total_sales': 'Total Sales',
      'orders_count': 'Total Orders',
      'active_products': 'Active Products',
      'new_orders': 'New Orders',
      'latest_orders': 'Latest Orders',
      'top_selling': 'Best Selling Products',
      'add_product_nav': 'Add Product',
      'manage_products_nav': 'Manage Products',
      'manage_orders_nav': 'Manage Orders',
      'store_settings_nav': 'Store Settings',
      'dashboard_nav': 'Dashboard',
      'products_nav': 'My Products',
      'orders_nav': 'Orders',

      // Merchant Features
      'add_new_product': 'Add New Product',
      'product_name': 'Product Name',
      'product_name_hint': 'Enter product name',
      'product_price': 'Product Price',
      'product_price_hint': 'Enter price in YER',
      'product_category': 'Category',
      'select_category': 'Select Category',
      'product_desc': 'Description',
      'product_desc_hint': 'Enter detailed product description...',
      'product_image': 'Product Image',
      'upload_image': 'Upload product image',
      'save_product': 'Save & Publish Product',
      'edit_product': 'Edit Product',
      'delete_product': 'Delete Product',
      'merchant_products': 'My Products',
      'merchant_orders': 'Received Orders',
      'store_setup': 'My Store Settings',
      'store_name': 'Store Name',
      'store_name_hint': 'Enter store name',
      'store_desc': 'Store Description',
      'store_desc_hint': 'Enter brief description of your store...',
      'store_phone': 'Store Contact Number',
      'store_address': 'Store Main Address',
      'save_store_settings': 'Save Store Settings',
      'order_id': 'Order ID',
      'customer': 'Customer',
      'status': 'Status',
      'order_details': 'Order Details',
      'order_status_pending': 'Pending',
      'order_status_accepted': 'Accepted',
      'order_status_shipped': 'Shipped',
      'order_status_completed': 'Completed',
      'order_status_cancelled': 'Cancelled',
      'change_status': 'Change Status',

      // Product Details
      'product_details': 'Product Details',
      'quantity': 'Quantity',
      'description': 'Description',
      'buy_now': 'Buy Now',
      'added_to_cart_msg': 'Product added to cart successfully!',

      // Notifications / Wishlist / Orders (User)
      'notifications': 'Notifications',
      'no_notifications': 'No new notifications',
      'my_wishlist': 'My Wishlist',
      'empty_wishlist': 'Wishlist is empty',
      'empty_wishlist_msg': 'Tap the heart icon on products to add them here',
      'my_orders': 'My Orders',
      'no_orders': 'No orders yet',

      // Checkout Extra
      'payment': 'Payment',
      'requested_products': 'Requested Products',
      'address_label': 'Address',
      'delivery_label': 'Delivery',
      'subtotal_products': 'Products Subtotal',
      'select_delivery_address': 'Select Delivery Address',
      'add_new_address': 'Add New Address',
      'select_delivery_method': 'Select Delivery Method',
      'enter_full_address': 'Enter full address',
      'add': 'Add',
      'select_address_msg': 'Please select delivery address',
      'order_confirmed_title': 'Order confirmed successfully!',
      'order_confirmed_msg': 'You will receive a notification when the order is prepared',
      'back_to_cart': 'Back to Cart',
      'fast_delivery': 'Fast Delivery',
      'normal_delivery': 'Normal Delivery',
      'store_pickup': 'Store Pickup',
      'al_kuraimi': 'Al Kuraimi',
      'yemen_kuwait': 'Yemen & Kuwait',
      'my_wallet_pay': 'Pay via\nMy Wallet',

      // Cart Extra
      'delete_all': 'Delete All',
      'products_count': 'Products',
      'free': 'Free',
      'continue_shopping': 'Continue Shopping',
      'clear_cart_title': 'Empty Cart',
      'clear_cart_msg': 'Are you sure you want to empty the shopping cart?',
      'cart_deleted_msg': 'Product deleted from cart',
      'cart_cleared_msg': 'Cart emptied',
      'cart_empty_error': 'Cart is empty, add some products first',

      // Dashboard Extra
      'search_here': 'Search here...',
      'select_your_location': 'Select your location',
      'confirm_location': 'Confirm location',
      'detecting_location': 'Detecting location...',
      'location_from_map': 'Custom location from map',
      'welcome_default': 'Welcome, Servant of Allah, Muhammad',
      'welcome_user': 'Welcome',
      'discount_promo': 'Discount 40% to 50%',
      'promo_available': 'Available now on the product',
      'all_colors': 'All colors',
      'shop_now_btn': 'Shop Now',
      'added_to_favorites': 'Added to favorites',
      'removed_from_favorites': 'Removed from favorites',
      'search_by_category': 'Search by category',
      'most_popular_brands': 'Most Popular Brands',
      'shop_by_brand': 'Shop by brand',
      'featured_for_you': 'Featured for you 🔥',
      'special_choices': 'Special choices',

      // Merchant Dashboard Extra
      'statistics': 'Statistics',
      'earnings': 'Earnings',
      'daily': 'Daily',

      // Merchant Orders Extra
      'view_details': 'View Details',
      'order_number': 'Order #',
      'suspend': 'Suspend',

      // Store Setup Extra
      'store_info': 'Store Info',
      'setup_store_intro': 'Start setting up your store with us',
      'complete_later': 'Complete later',
      'next': 'Next',
      'finish': 'Finish',
      'select_activity_type': 'Select activity type',
      'add_logo_here': 'Add your logo here',
      'update_location': 'Update location',
      'select_address': 'Select address',
      'primary': 'Primary',
      'add_branch': 'Add branch',

      // Notifications Extra
      'today': 'Today',
      'yesterday': 'Yesterday',
      'mark_as_read': 'Mark as read',
      'notification_type_promo': 'Promo Alert',
      'notification_type_order': 'Order Update',
      'notification_type_admin': 'Admin Message',
      'notification_type_remind': 'Reminder',
      'notification_type_welcome': 'Welcome',
      'notification_title_1': 'Exclusive Offers for You!',
      'notification_title_2': 'Your order has been shipped',
      'notification_title_3': 'Privacy Policy Update',
      'notification_title_4': 'Weekend Discounts',
      'notification_title_5': 'Items in your cart',
      'notification_title_6': 'Welcome to Tujjar Forum',
      'notification_desc_1': 'Browse the latest products and special offers at unbeatable prices.',
      'notification_desc_2': 'Your order #1024 is on its way, track it now.',
      'notification_desc_3': 'Please review the new updates to the privacy policy.',
      'notification_desc_4': 'Enjoy discounts up to 50% off in all departments.',
      'notification_desc_5': 'Do not forget to complete your purchase of the items in your cart.',
      'notification_desc_6': 'We are glad you joined us, start shopping now!',
      'time_2h_ago': '2 hours ago',
      'time_4h_ago': '4 hours ago',
      'time_8h_ago': '8 hours ago',
      'time_10h_ago': '10 hours ago',
      'time_yesterday_morning': 'Yesterday 09:30 AM',
      'time_yesterday_early': 'Yesterday 08:00 AM',

      // Products Extra
      'completed': 'Completed',
      'colors': 'Colors',
      'sizes': 'Sizes',
      'buy_product': 'Buy Product',
      'ratings': 'ratings',
      'wishlist_limit_msg': 'Cannot pin more than 10 products',

      // Mock Data
      'mock_order_date': 'Thursday, April 7, 2026 • 10:25 AM',
      'mock_address_1': 'Riyadh Street, near Golden Pen Library',
      'mock_address_2': 'Al-Ribat Street, near Golden Pen Library',
      'mock_address_3': 'Sixty Street, opposite Towers Complex',
      'mock_address_4': 'Al-Saadah District, Al-Nakheel Street, Bldg 5',
      'mock_address_5': 'Al-Ribat Street, Al-Razi University',
      'mock_product_name': 'Product name with five words or more',
      'mock_product_short': 'Product name with five words',
      'mock_product_modern': 'Modern Product',
      'mock_product_modern_style': 'Modern Style T-Shirt',
      'mock_product_modern_tshirt': 'Modern T-Shirt',
      'mock_product_test': 'Test Product Name',
      'mock_product_desc': 'Cotton shirt with simple and elegant design, comfortable for daily wear and suits all looks.',

      // Category Names
      'men_clothing': "Men's Clothing",
      'women_clothing': "Women's Clothing",
      'handbags': 'Handbags',
      'shoes_cat': 'Shoes',
      'children_clothing': "Children's Clothing",
      'accessories': 'Accessories',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['ar', 'en'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppLocalizationsExtension on BuildContext {
  String tr(String key) => AppLocalizations.of(this)?.translate(key) ?? key;
}
